#ifndef CODIGOSRET_H_INCLUDED
#define CODIGOSRET_H_INCLUDED

#define TODO_OK 0
#define ERR_ARCHIVO -1
#define SIN_MEM -2
#define ERR_LINEA_LARGA -3

#define NO_ENCONTRADO -1

#endif // CODIGOSRET_H_INCLUDED
